const data = [
    {
        id : 1,
        "brend" : "gucci",
        "for" : "мужу",
        "developments" : "свадьба",
        "collection" : "кольцо",
        "season" : "лето",
        "price" : "10",
        "rarity" : "5",
        "img" : "https://ae04.alicdn.com/kf/Hdb232e7f2b164285935a377ef72a2eb0l.jpg_350x350.jpg",
    },
    {
        id : 2,
        "brend" : "dolce  gabanna",
        "for" : "жене",
        "developments" : "от себя",
        "collection" : "браслет",
        "season" : "зима",
        "price" : "30",
        "rarity" : "10",
        "img" : "https://tangogold.com.ua/content/goods/4921/picture-4921.jpg",
    },
    {
        id : 3,
        "brend" : "luivitton",
        "for" : "партнеру",
        "developments" : "день рождения",
        "collection" : "цепочка",
        "season" : "весна",
        "price" : "50",
        "rarity" : "8",
        "img" : "https://basket-02.wb.ru/vol173/part17366/17366823/images/big/2.jpg",
    },
    {
        id : 4,
        "brend" : "gucci",
        "for" : "папе",
        "developments" : "от себя",
        "collection" : "браслет",
        "season" : "осень",
        "price" : "100",
        "rarity" : "5",
        "img" : "https://images.prom.ua/2430115448_w640_h640_muzhskoj-shirokij-braslet.jpg",
    },
    {
        id : 5,
        "brend" : "ballenciaga",
        "for" : "маме",
        "developments" : "день рождения",
        "collection" : "серьги",
        "season" : "лето",
        "price" : "200",
        "rarity" : "3",
        "img" : "https://7karat.by/upload/medialibrary/f2d/f2d6fbb7966e25ba1bc36fdedb20d96e.png",
    },
    {
        id : 6,
        "brend" : "dolce  gabanna",
        "for" : "мужу",
        "developments" : "свадьба",
        "collection" : "кольцо",
        "season" : "весна",
        "price" : "20",
        "rarity" : "7",
        "img" : "https://diamant.ua/uploads/a0/37/a037cdec2d172730ce176586495a588f.jpg",
    },
    {
        id : 7,
        "brend" : "gucci",
        "for" : "жене",
        "developments" : "свадьба",
        "collection" : "серьги",
        "season" : "лето",
        "price" : "250",
        "rarity" : "7",
        "img" : "https://www.alltime.ru/obj/article/image-blog/wedding-earrings/wedding-earrings_2.jpg",
    },
    {
        id : 8,
        "brend" : "balenciaga",
        "for" : "мужу",
        "developments" : "день рождение",
        "collection" : "браслет",
        "season" : "осень",
        "price" : "50",
        "rarity" : "8",
        "img" : "https://www.alltime.ru/obj/article/image-blog/mozhno_li_darit_braslet/mozhno_li_darit_braslet_2.jpg",
    },
    {
        id : 9,
        "brend" : "luivitton",
        "for" : "маме",
        "developments" : "день рождение",
        "collection" : "кольцо",
        "season" : "весна",
        "price" : "120",
        "rarity" : "10",
        "img" : "https://ae04.alicdn.com/kf/Hb0e9c9c09b76460480d8bdb2c8e4a599a/-.jpg_640x640.jpg",
    },
    {
        id : 10,
        "brend" : "gucci",
        "for" : "мужу",
        "developments" : "свадьба",
        "collection" : "кольцо",
        "season" : "весна",
        "price" : "50",
        "rarity" : "7",
        "img" : "https://bgs.kiev.ua/wp-content/uploads/Razmery-obruchalnykh-kolets-87-Bz.jpg",
    },
    {
        id : 11,
        "brend" : "balenciaga",
        "for" : "жене",
        "developments" : "день рождение",
        "collection" : "серьги",
        "season" : "лето",
        "price" : "150",
        "rarity" : "10",
        "img" : "https://zoodmall.com/cdn-cgi/image/w=500,fit=contain,f=auto/https://images.zoodmall.com/cloudinary/f1/063/http%253A%252F%252Fimages.kent2015.com%252Fimages%252F20%252F08%252Fv%252F51005597%252F6.jpg",
    },
    {
        id : 12,
        "brend" : "dolce  gabanna",
        "for" : "партнеру",
        "developments" : "от себя",
        "collection" : "браслет",
        "season" : "зима",
        "price" : "20",
        "rarity" : "5",
        "img" : "https://ae01.alicdn.com/kf/Hb763fb67423047ed8bbde8cdbd6b68a7C.jpg",
    },
    {
        id : 13,
        "brend" : "gucci",
        "for" : "жене",
        "developments" : "от себя",
        "collection" : "цепочка",
        "season" : "весна",
        "price" : "120",
        "rarity" : "8",
        "img" : "https://84.img.avito.st/image/1/1.PZlUsbaBkXAiFGN2Iu042JcSlXb2FJF2kXGVdiIUY3biFp104hCRNA.jedeDku0Br4HvCn8mVic2Rbp-uijuva4fc_kK0UTBM8",
    },

]